# Site settings
title: "琳儿的手记"
description: "咖喱 Gay Gay"
baseurl: "" # required if used under gh-pages branch, else (under master branch) just leave empty/blank
url: ""
author: "liner"
cover_url: "/cover.jpg"


# Collections
collections:
  instalife:

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave empty to disable it

plugins:
  - jekyll-sitemap

exclude: ["LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script"]

############################################################
